# Generated by Django 6.0.6 on 2026-07-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_meta_description_post_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_alt_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
