# Generated by Django 5.1.7 on 2026-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='team/images/')),
                ('member_type', models.CharField(choices=[('board_member', 'Board Member'), ('staff', 'Staff')], default='board_member', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
