# Generated by Django 6.0.6 on 2026-08-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teammember_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('board_member', 'Board Member'), ('staff', 'Staff'), ('former_staff', 'Former Staff')], default='board_member', max_length=50),
        ),
    ]
