# Generated by Django 6.0.6 on 2026-08-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teammember_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
