# Generated by Django 6.0.6 on 2026-08-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_teammember_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
