# Generated by Django 6.0.6 on 2026-08-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_teammember_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
