# Generated by Django 6.0.6 on 2026-08-27 08:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fellowship', 'Fellowship'), ('Internship', 'Internship'), ('Grants', 'Grants'), ('Vacancy', 'Vacancy')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to='opportunity/images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('apply_by', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
