# Generated by Django 6.0.6 on 2026-08-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
