# Generated by Django 6.0.6 on 2026-07-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpowermentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empowerment Program',
                'verbose_name_plural': 'Empowerment Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmpowermentProgramCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='empowerment_program/cohorts/')),
                ('image_alt_description', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='empowerment_program.empowermentprogram')),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CohortVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='empowerment_program/cohort_volunteers/')),
                ('image_alt_description', models.CharField(blank=True, max_length=255, null=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='empowerment_program.empowermentprogramcohort')),
            ],
            options={
                'verbose_name': 'Cohort Volunteer',
                'verbose_name_plural': 'Cohort Volunteers',
                'ordering': ['created_at'],
            },
        ),
    ]
