# Generated by Django 6.0.6 on 2026-07-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('thumbnail_image', models.FileField(blank=True, null=True, upload_to='event_reports/thumbnail')),
                ('thumbnail_alt_description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='event_reports/files')),
                ('file_alt_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Report',
                'verbose_name_plural': 'Event Reports',
            },
        ),
    ]
