# Generated by Django 6.0.6 on 2026-07-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='file_alt_description',
        ),
    ]
