# Generated by Django 6.0.6 on 2026-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_report', '0002_remove_eventreport_file_alt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
